import { z } from 'zod';

/**
 * Linaw message contract, version 1.
 *
 * Every JSON message on the WebSocket between the UI and the local backend
 * (ws://localhost:8765) must match one of the schemas below. Audio is the only
 * thing sent outside this contract: raw binary frames from the UI after a
 * `session.start`, encoded as the `mimeType` it announced.
 *
 * Times (`t`) are seconds since the session started.
 */
export const CONTRACT_VERSION = 1;
export const DEFAULT_PORT = 8765;

const v = z.literal(CONTRACT_VERSION);
const id = z.string().min(1);
const seconds = z.number().nonnegative();

// ---------------------------------------------------------------- shared

export const StatusSchema = z.enum(['waiting', 'listening', 'stopped', 'offline']);
export type Status = z.infer<typeof StatusSchema>;

export const ExplanationLevelSchema = z.enum(['simple', 'detailed']);
export type ExplanationLevel = z.infer<typeof ExplanationLevelSchema>;

export const LanguageSchema = z.enum(['tl', 'en']);
export type Language = z.infer<typeof LanguageSchema>;

export const PreferencesSchema = z.object({
  level: ExplanationLevelSchema,
  language: LanguageSchema,
});
export type Preferences = z.infer<typeof PreferencesSchema>;

export const TermRefSchema = z.object({
  /** Exact text of the term as it appears in the segment. */
  text: z.string().min(1),
  /**
   * Card that explains (or will explain) it. The UI treats the term as pending
   * until a `card` with this id arrives. Absent when no card is planned.
   */
  cardId: id.optional(),
});
export type TermRef = z.infer<typeof TermRefSchema>;

export const CardSchema = z.object({
  id,
  term: z.string().min(1),
  /** `checked` = from the verified glossary; `ai` = generated by the model. */
  kind: z.enum(['checked', 'ai']),
  meaning: z.string().min(1),
  example: z.string().min(1),
  /** What the term means in the current moment of the hearing. */
  now: z.string().min(1),
  t: seconds,
  language: LanguageSchema,
  /**
   * The law or rule the meaning is based on, as a citation the user can look up,
   * e.g. "Rules on Evidence, Rule 130, Sec. 37". Absent when no passage backs it.
   */
  basis: z.string().min(1).max(200).optional(),
});
export type Card = z.infer<typeof CardSchema>;

/**
 * Transcript segment ids that back a claim. The UI shows them as quotes
 * the user can jump to, so summaries and answers can be checked.
 */
export const SourcesSchema = z.array(id);

export const TranslationSchema = z.object({
  language: LanguageSchema,
  text: z.string().min(1),
});
export type Translation = z.infer<typeof TranslationSchema>;

export const SummaryEventSchema = z.object({
  t: seconds,
  title: z.string().min(1),
  detail: z.string().min(1),
  sources: SourcesSchema.optional(),
});
export type SummaryEvent = z.infer<typeof SummaryEventSchema>;

// ------------------------------------------------------ server -> client

export const StatusMessageSchema = z.object({
  v,
  type: z.literal('status'),
  status: StatusSchema,
  /** Optional session title, e.g. "Impeachment Trial — Day 3". */
  title: z.string().optional(),
});

export const TranscriptSegmentMessageSchema = z.object({
  v,
  type: z.literal('transcript.segment'),
  id,
  t: seconds,
  speaker: z.string().min(1),
  text: z.string().min(1),
  terms: z.array(TermRefSchema),
  /** `false` while the segment is still being spoken; re-sent with the same id. */
  final: z.boolean(),
  /** `text` translated into the user's `preferences.language`, when it was spoken in another language. */
  translation: TranslationSchema.optional(),
});

export const CardPendingMessageSchema = z.object({
  v,
  type: z.literal('card.pending'),
  id,
  term: z.string().min(1),
  t: seconds,
});

export const CardMessageSchema = z.object({
  v,
  type: z.literal('card'),
  /** A card whose id matches an earlier `card.pending` or card replaces it. */
  card: CardSchema,
  /** Set when this card answers a `card.simplify` request. */
  requestId: id.optional(),
});

/**
 * The explanation promised by a `card.pending` with this id won't come (the model failed).
 * The UI drops the pending card and stops marking the term as being explained.
 */
export const CardFailedMessageSchema = z.object({
  v,
  type: z.literal('card.failed'),
  id,
});

export const WhatSaidResultMessageSchema = z.object({
  v,
  type: z.literal('what_said.result'),
  requestId: id,
  windowSec: z.number().positive(),
  points: z.array(z.string().min(1)).min(1),
  sources: SourcesSchema.optional(),
});

export const SummaryResultMessageSchema = z.object({
  v,
  type: z.literal('summary.result'),
  requestId: id,
  overview: z.string().min(1),
  events: z.array(SummaryEventSchema),
  /** Short "where things stand" note on an unresolved issue, if any. */
  openIssue: z.string().optional(),
});

export const AnswerMessageSchema = z.object({
  v,
  type: z.literal('answer'),
  requestId: id,
  question: z.string().min(1),
  text: z.string().min(1),
  sources: SourcesSchema.optional(),
});

export const ErrorMessageSchema = z.object({
  v,
  type: z.literal('error'),
  code: z.enum(['bad_request', 'unsupported_audio', 'model_unavailable', 'internal']),
  message: z.string(),
  requestId: id.optional(),
});

export const ServerMessageSchema = z.discriminatedUnion('type', [
  StatusMessageSchema,
  TranscriptSegmentMessageSchema,
  CardPendingMessageSchema,
  CardMessageSchema,
  CardFailedMessageSchema,
  WhatSaidResultMessageSchema,
  SummaryResultMessageSchema,
  AnswerMessageSchema,
  ErrorMessageSchema,
]);
export type ServerMessage = z.infer<typeof ServerMessageSchema>;

// ------------------------------------------------------ client -> server

export const SessionStartMessageSchema = z.object({
  v,
  type: z.literal('session.start'),
  /** `tab` = a shared browser tab, `file` = a local recording, `system` = everything playing on the computer (desktop overlay). */
  source: z.enum(['tab', 'file', 'system']),
  /** Encoding of the binary audio frames that follow, e.g. "audio/webm;codecs=opus". */
  mimeType: z.string().min(1),
  preferences: PreferencesSchema,
});

export const SessionStopMessageSchema = z.object({
  v,
  type: z.literal('session.stop'),
});

export const PreferencesUpdateMessageSchema = z.object({
  v,
  type: z.literal('preferences.update'),
  preferences: PreferencesSchema,
});

export const WhatSaidRequestMessageSchema = z.object({
  v,
  type: z.literal('what_said.request'),
  requestId: id,
  windowSec: z.number().positive(),
});

export const SummaryRequestMessageSchema = z.object({
  v,
  type: z.literal('summary.request'),
  requestId: id,
});

export const AskMessageSchema = z.object({
  v,
  type: z.literal('ask'),
  requestId: id,
  question: z.string().min(1).max(500),
});

/**
 * A question asked out loud (push to talk). The backend transcribes it, then answers it like `ask`:
 * the `answer` carries the words it heard as `question`. If it heard no question, it replies with
 * `error` (`unsupported_audio`) and the same `requestId`.
 */
export const AskAudioMessageSchema = z.object({
  v,
  type: z.literal('ask.audio'),
  requestId: id,
  /** Encoding of `audio`, e.g. "audio/webm;codecs=opus". */
  mimeType: z.string().min(1),
  /**
   * One short recording (up to about 30 s), base64. The one exception to "audio is binary frames":
   * binary frames are the live hearing, and a one-off clip in its own message can't be mixed up with it.
   */
  audio: z.string().min(1).max(2_000_000),
});

export const CardSimplifyMessageSchema = z.object({
  v,
  type: z.literal('card.simplify'),
  requestId: id,
  cardId: id,
});

export const ClientMessageSchema = z.discriminatedUnion('type', [
  SessionStartMessageSchema,
  SessionStopMessageSchema,
  PreferencesUpdateMessageSchema,
  WhatSaidRequestMessageSchema,
  SummaryRequestMessageSchema,
  AskMessageSchema,
  AskAudioMessageSchema,
  CardSimplifyMessageSchema,
]);
export type ClientMessage = z.infer<typeof ClientMessageSchema>;

// ---------------------------------------------------------------- helpers

type DistributiveOmit<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;

/** A message without its `v` field, for building messages before `withVersion`. */
export type Unversioned<T> = DistributiveOmit<T, 'v'>;

export function withVersion<T extends object>(message: T): T & { v: typeof CONTRACT_VERSION } {
  return { v: CONTRACT_VERSION, ...message };
}

export type ParseResult<T> = { ok: true; message: T } | { ok: false; error: string };

function parseWith<T>(schema: z.ZodType<T, z.ZodTypeDef, unknown>, raw: string): ParseResult<T> {
  let data: unknown;
  try {
    data = JSON.parse(raw);
  } catch {
    return { ok: false, error: 'not valid JSON' };
  }
  const result = schema.safeParse(data);
  if (result.success) return { ok: true, message: result.data };
  const error = result.error.issues
    .map((issue) => `${issue.path.join('.') || '(root)'}: ${issue.message}`)
    .join('; ');
  return { ok: false, error };
}

export const parseServerMessage = (raw: string) => parseWith(ServerMessageSchema, raw);
export const parseClientMessage = (raw: string) => parseWith(ClientMessageSchema, raw);
